### ISSUE TITLE
502 Bad Gateway.

### ISSUE THREAD

**Issue by matbandeli** [HE-Arc/YC_Movies#6]
le déploiment passe sans erreur mais il y a une erreur 502 Bad Gateway.

**Comment by greut** [comment]
Ah bon.

et les logs?

**Comment by matbandeli** [comment]
![capture6](https://cloud.githubusercontent.com/assets/11160279/24034527/e2329aac-0af1-11e7-964b-0c31b545eeec.PNG)

Je pense que j'ai oublié la commande pour redémarrer puma

**Comment by greut** [comment]
Vous avez maintenant une erreur 500 donnée par Rails. Il y a également des _logs_ dans l'application elle-même.

**Comment by matbandeli** [comment]
oui effectivement, par contre les logs ne disent pas grand chose. Je suis pourtant en mode :debug.

![capture7](https://cloud.githubusercontent.com/assets/11160279/24039091/2b480c06-0b04-11e7-833c-2de9ea0f4747.PNG)

**Comment by greut** [comment]
Pas de puma.

```console
yoan@ycmovies:~/www$ pstree
tini─┬─ruby2.4───{ruby-timer-thr}
     └─runsvdir─┬─runsv
                ├─runsv───syslog-ng
                ├─runsv───nginx───2*[nginx]
                ├─runsv───cron
                └─runsv───sshd───2*[sshd───sshd───bash]
```

**Comment by matbandeli** [comment]
Ca marche, merci d'avoir réinstallé la gem puma.

**Comment by greut** [comment]
J'ai dû faire deux choses :

1. modifier `/etc/service/puma/run`
2. installer `puma` de manière globale.

Voilà... ça le fait à présent.

https://ycmovies.srvz-webapp.he-arc.ch/
