### ISSUE TITLE
Variables d'environnement

### ISSUE THREAD

**Issue by matbandeli** [HE-Arc/YC_Movies#7]
## en local (env. de dévelopment) : 

- Je set mes variables d'environnement dans le `.bashrc` 
```
export USER='matthieu'
export GROUPNAME='hearc'
export PASSWORD='.............'
export RECAPTCHA_SITE_KEY='..................................'
export RECAPTCHA_SECRET_KEY='.............................'
```
- Je lance rails en local `rails s`

- Tout va bien (la base de données comme le captcha)

## Problème sur srvz (env. de production)

- J'exporte les 2 variables RECAPTCHA dans le fichier `.bash_profile` à la fin des autres exports : 
```
export RECAPTCHA_SITE_KEY='..................................'
export RECAPTCHA_SECRET_KEY='.............................'
```
- Le captcha ne fonctionne pas, sauf si je lui passe la clé en dur dans le code : 
`<%= recaptcha_tags    :site_key   =>  '............' %>`

### remarques : 

- je n'arrive pas à lire les variables d'environnement sur srvz, exemple : 
`<%= ENV['GROUPNAME'] %>` => hearc (en local)
`<%= ENV['GROUPNAME'] %>` => "rien" (sur srvz)

- le problème avec mon cpatcha vient très certainement des variables d'environnement.

**Comment by greut** [comment]
_srvz_ ne lit pas **votre fichier** `.bashrc`, jetez un œil à `puma.rb` et `/etc/service/puma/run`.

**Comment by matbandeli** [comment]
On dirait qu'elles se trouvent dans /etc/container_environnement/
Il s'agit des export du fichier `.bash_profile` ?
Je peux les regénérer en y incluant mes variables?


**edit:** J'ai ajouté les fichiers à la main, ça fonctionne! ;) merci beaucoup

**Comment by greut** [comment]
@matbandeli top.
